import React from 'react';
import PageHeader from '../components/common/PageHeader';
import Card from '../components/common/Card';
import { Scale, CheckCircle2, AlertTriangle, FileCode, Server } from 'lucide-react';

export default function TermsOfService() {
  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <PageHeader
        title="Terms of Service"
        subtitle="Operational agreement governing platform usage, model outputs, and API access."
      />

      <Card className="p-6 sm:p-8 space-y-6 text-slate-300 text-sm leading-relaxed">
        <div className="border-b border-navy-800 pb-4">
          <p className="text-xs font-mono text-slate-400">Effective Date: October 1, 2026 | Platform Version: 1.0.0</p>
          <p className="text-xs font-mono text-cyanAccent mt-1">Domain: app.churnlens.io</p>
        </div>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-slate-100 flex items-center gap-2">
            <Scale className="h-4 w-4 text-cyanAccent" />
            1. Platform License and Usage
          </h2>
          <p>
            ChurnLens grants authorized users a non-exclusive license to operate the web interface, 
            run batch scoring workflows, and integrate with backend REST endpoints for internal business 
            retention planning and risk evaluation.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-slate-100 flex items-center gap-2">
            <AlertTriangle className="h-4 w-4 text-amber-400" />
            2. Statistical Modeling Disclaimer
          </h2>
          <p>
            All churn probabilities, risk tiers, and TreeSHAP attribution outputs generated by ChurnLens 
            are statistical estimates based on historical correlation. Outputs do not constitute financial, 
            legal, or guaranteed customer behavior forecasts. Counterfactual simulations illustrate model 
            response functions and do not guarantee causal retention outcomes in commercial deployments.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-slate-100 flex items-center gap-2">
            <Server className="h-4 w-4 text-cyanAccent" />
            3. API Availability and Rate Limits
          </h2>
          <p>
            Self-hosted and containerized instances are subject to local resource constraints. Organizations 
            are responsible for maintaining adequate compute and memory capacity for batch scoring workloads 
            exceeding 10,000 records.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-slate-100 flex items-center gap-2">
            <CheckCircle2 className="h-4 w-4 text-cyanAccent" />
            4. Permitted and Prohibited Conduct
          </h2>
          <p>
            Users agree not to submit malicious payloads, corrupted binary streams, or intentionally malformed 
            CSV documents designed to disrupt FastAPI server worker threads. Batch files must comply with the 
            documented Telco customer feature schema.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-slate-100 flex items-center gap-2">
            <FileCode className="h-4 w-4 text-cyanAccent" />
            5. Governing Law and Amendments
          </h2>
          <p>
            These terms are governed by standard enterprise software licensing conventions. Revisions to these 
            terms will be recorded in the platform release documentation.
          </p>
        </section>
      </Card>
    </div>
  );
}
